### ISSUE TITLE
Guzzle 6.2.2 compatibility error.

### ISSUE THREAD

**Issue by ernesthernandez** [LeaguePHP/LeagueWrap#12]
Please update to Guzzle 6.2.2, I got these error:   conflict with your requirements or minimum-stability.

Test and work perfectly in this version.
Thanks!

**Comment by m1so** [comment]
Try using the master branch until we release a new version, it already has [Guzzle 6.2.2](https://github.com/LeaguePHP/LeagueWrap/blob/master/composer.json#L18)
