### ISSUE TITLE
"Forbidden" error

### ISSUE THREAD

**Issue by alberas** [LeaguePHP/LeagueWrap#18]
Hello,
I was testing the league API and received a "Forbidden" in my screen. I checked at Riot Developers and the API was really down.
I tried to catch the errer with LeagueWrap\Response\Http401 but didn't work.
Any suggestions?

**Comment by m1so** [comment]
Check what exception gets thrown or catch one of the parent exceptions from https://github.com/LeaguePHP/LeagueWrap/blob/master/src/LeagueWrap/Response
