### ISSUE TITLE
Guzzle 6.2 incompatible

### ISSUE THREAD

**Issue by backendrulz** [LeaguePHP/LeagueWrap#2]
```
  Problem 1
    - Installation request for league-php/leaguewrap ^0.7.0 -> satisfiable by league-php/leaguewrap[0.7.0].
    - league-php/leaguewrap 0.7.0 requires guzzlehttp/guzzle ~6.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.0, 6.1.1] but these conflict with your requirements or minimum-stability.

```
Using Laravel 5.3 base.

```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "guzzlehttp/guzzle": "^6.2"
    },
```

**Comment by dnlbauer** [comment]
You are requiring guzzle 6.2 while leaguewrap requires 6.1. The versions
are conflicting and therefor you can't load it. You either have to change
your own requirement to 6.1 or test if this wrapper also works with 6.2 and
load it manually.

Cristian Ferreyra notifications@github.com schrieb am So., 13. Nov. 2016,
21:53:

**Comment by m1so** [comment]
We can also update to guzzle 6.2 in the future, there have been [no breaking changes](https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md#620---2016-03-21) and [tests pass](https://travis-ci.org/LeaguePHP/LeagueWrap/builds/175571521). What do you think @danijoo?

As of right now there is a `guzzle-6.2` branch @SnakeSaurio

**Comment by dnlbauer** [comment]
Sure!

Michal Baumgartner notifications@github.com schrieb am Mo., 14. Nov.
2016, 00:27:
