### ISSUE TITLE
Getting only single Static Data 

### ISSUE THREAD

**Issue by Kaz-** [LeaguePHP/LeagueWrap#4]
Hello. 

I'm using `$this->api->attachStaticData()`; to attach Static Datas to my requests, but it seems there's a little issue with it. 

For exemple when I call game api I only get a single Summoner Spell. (same issue with Items)

    $gameApi = $this->api->game();
    $lastGames = $gameApi->recent($summoner);

This actually returns the following : 

    "summonerSpellStaticData": {
         "info": {
            "name": "Flash",
            "description": "Teleports your champion a short distance toward your cursor's location.",
            "summonerLevel": 8,
            "id": 4,
            "key": "SummonerFlash"
           }
    }

Am I doing something wrong ? Or is it a bug ? 

I'm trying to dig up into source code, but it's a bit complicated for someone who isn't in the project :/ 

Do you guys have the same issue , or is it something in my app going wrong ?

**Comment by nohanna** [comment]
I have the same issue, it returns only one StaticData on summoner spells and items.
I don't think this is your app.

**Comment by m1so** [comment]
[This](https://github.com/LeaguePHP/LeagueWrap/commit/e9a6f700c1bd42764da718f071037bb4f4e455ca) should fix the issue. Now `summonerSpellStaticData` etc. should be an array of objects like so:

<img width="1576" alt="screen shot 2016-11-19 at 23 59 25" src="https://cloud.githubusercontent.com/assets/983741/20459022/734698c6-aeb4-11e6-97d7-e8e5d234589d.png">

Let me know if it would be better for your usecase to use associative array with `id` as key @Kaz- @nohanna

**Comment by nohanna** [comment]
Good for me. Thank you @m1so for your help !
